# Generated by Django 6.0.1 on 2026-01-13 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingPermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_year', models.CharField(blank=True, default='', max_length=10)),
                ('permit_no', models.CharField(max_length=64, unique=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('district', models.CharField(blank=True, default='', max_length=32)),
                ('section', models.CharField(blank=True, default='', max_length=64)),
                ('subsection', models.CharField(blank=True, default='', max_length=64)),
                ('parcel_no', models.CharField(blank=True, default='', max_length=32)),
                ('build_type', models.CharField(blank=True, default='', max_length=32)),
                ('structure', models.CharField(blank=True, default='', max_length=128)),
                ('zoning', models.CharField(blank=True, default='', max_length=128)),
                ('location', models.CharField(blank=True, default='', max_length=256)),
                ('land_text', models.TextField(blank=True, default='')),
                ('building_info', models.TextField(blank=True, default='')),
                ('summary', models.TextField(blank=True, default='')),
                ('building_area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('arcade_site_area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('other_site_area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('build_deadline', models.CharField(blank=True, default='', max_length=64)),
                ('project_cost', models.BigIntegerField(blank=True, null=True)),
                ('owner', models.CharField(blank=True, default='', max_length=256)),
                ('designer', models.CharField(blank=True, default='', max_length=256)),
                ('supervisor', models.CharField(blank=True, default='', max_length=256)),
                ('misc_works', models.TextField(blank=True, default='')),
                ('applicable_law', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['district', 'section', 'subsection'], name='hub_buildin_distric_a5dcb8_idx'), models.Index(fields=['district', 'section'], name='hub_buildin_distric_18bc61_idx'), models.Index(fields=['designer'], name='hub_buildin_designe_55b59c_idx'), models.Index(fields=['zoning'], name='hub_buildin_zoning_bbcf12_idx')],
            },
        ),
        migrations.CreateModel(
            name='WreApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approve_date', models.DateField(blank=True, null=True)),
                ('district', models.CharField(blank=True, default='', max_length=32)),
                ('section', models.CharField(blank=True, default='', max_length=64)),
                ('subsection', models.CharField(blank=True, default='', max_length=64)),
                ('parcel_no', models.CharField(blank=True, default='', max_length=32)),
                ('address', models.CharField(blank=True, default='', max_length=256)),
                ('site_area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('site_area_ping', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['district', 'section', 'subsection', 'parcel_no'], name='hub_wreappr_distric_9d11c4_idx'), models.Index(fields=['approve_date'], name='hub_wreappr_approve_edd90e_idx')],
            },
        ),
        migrations.CreateModel(
            name='WrePermitMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(choices=[('exact', 'Exact'), ('multi_parcel', 'Multi-parcel')], max_length=32)),
                ('rule_ok', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.buildingpermit')),
                ('wre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.wreapproval')),
            ],
            options={
                'indexes': [models.Index(fields=['match_type', 'rule_ok'], name='hub_wreperm_match_t_ebd952_idx')],
                'unique_together': {('wre', 'permit', 'match_type')},
            },
        ),
    ]
