# Generated by Django 6.0.1 on 2026-01-13 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrbanRenewalCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='taipei_ur', max_length=32)),
                ('district', models.CharField(blank=True, default='', max_length=32)),
                ('section', models.CharField(blank=True, default='', max_length=64)),
                ('subsection', models.CharField(blank=True, default='', max_length=64)),
                ('parcel_no', models.CharField(blank=True, default='', max_length=32)),
                ('address', models.CharField(blank=True, default='', max_length=256)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('site_area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('site_area_ping', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['district', 'section', 'subsection'], name='hub_urbanre_distric_328f45_idx'), models.Index(fields=['approved_date'], name='hub_urbanre_approve_338d93_idx')],
            },
        ),
        migrations.CreateModel(
            name='UrbanRenewalBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('structure', '結構評估'), ('seismic', '耐震設計'), ('green', '綠建築'), ('smart', '智慧建築'), ('barrierfree', '無障礙'), ('donation', '捐贈公設'), ('schedule', '時程獎勵'), ('scale', '規模獎勵'), ('other', '其他')], max_length=32)),
                ('bonus_pct', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='hub.urbanrenewalcase')),
            ],
            options={
                'indexes': [models.Index(fields=['code'], name='hub_urbanre_code_5c5a7f_idx')],
                'unique_together': {('case', 'code')},
            },
        ),
    ]
