# Generated by Django 6.0.1 on 2026-01-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_urbanrenewalcase_urbanrenewalbonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='urbanrenewalcase',
            name='case_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
