# Generated by Django 6.0.1 on 2026-01-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_urbanrenewalcase_case_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='urbanrenewalcase',
            name='total_bonus_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
