# Generated by Django 6.0.1 on 2026-01-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_urbanrenewalcase_total_bonus_pct'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsePermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_year', models.CharField(blank=True, default='', max_length=10)),
                ('permit_no', models.CharField(max_length=64, unique=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('district', models.CharField(blank=True, default='', max_length=32)),
                ('section', models.CharField(blank=True, default='', max_length=64)),
                ('subsection', models.CharField(blank=True, default='', max_length=64)),
                ('parcel_no', models.CharField(blank=True, default='', max_length=64)),
                ('build_type', models.CharField(blank=True, default='', max_length=64)),
                ('structure', models.CharField(blank=True, default='', max_length=256)),
                ('zoning', models.CharField(blank=True, default='', max_length=256)),
                ('location', models.CharField(blank=True, default='', max_length=256)),
                ('owner', models.CharField(blank=True, default='', max_length=256)),
                ('designer', models.CharField(blank=True, default='', max_length=256)),
                ('supervisor', models.CharField(blank=True, default='', max_length=256)),
                ('building_area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('other_site_area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['permit_year'], name='hub_useperm_permit__682345_idx'), models.Index(fields=['district', 'section', 'subsection'], name='hub_useperm_distric_27a727_idx'), models.Index(fields=['designer'], name='hub_useperm_designe_140b17_idx')],
            },
        ),
    ]
