# Generated by Django 6.0.1 on 2026-01-15 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0005_usepermit'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingUsePermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_year', models.CharField(max_length=16, verbose_name='執照年度')),
                ('permit_no', models.CharField(max_length=64, verbose_name='執照號碼')),
                ('issue_date_text', models.CharField(blank=True, default='', max_length=32, verbose_name='發照日期')),
                ('original_permit_no', models.CharField(blank=True, default='', max_length=128, verbose_name='原核發執照')),
                ('designer', models.CharField(blank=True, default='', max_length=128, verbose_name='設計人')),
                ('supervisor', models.CharField(blank=True, default='', max_length=128, verbose_name='監造人')),
                ('contractor', models.CharField(blank=True, default='', max_length=128, verbose_name='承造人')),
                ('build_type', models.CharField(blank=True, default='', max_length=64, verbose_name='建造類別')),
                ('structure_type', models.CharField(blank=True, default='', max_length=64, verbose_name='構造種類')),
                ('zoning', models.CharField(blank=True, default='', max_length=128, verbose_name='使用分區')),
                ('building_count', models.IntegerField(blank=True, null=True, verbose_name='棟數')),
                ('block_count', models.IntegerField(blank=True, null=True, verbose_name='幢數')),
                ('floors_above', models.IntegerField(blank=True, null=True, verbose_name='地上層數')),
                ('floors_below', models.IntegerField(blank=True, null=True, verbose_name='地下層數')),
                ('unit_count', models.IntegerField(blank=True, null=True, verbose_name='戶數')),
                ('arcade_site_area_sqm', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='騎樓基地面積（㎡）')),
                ('other_site_area_sqm', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='其他基地面積（㎡）')),
                ('footprint_area_sqm', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='建築面積（㎡）')),
                ('legal_open_space_sqm', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='法定空地面積（㎡）')),
                ('refuge_area_above_sqm', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='地上避難面積（㎡）')),
                ('refuge_area_below_sqm', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='地下避難面積（㎡）')),
                ('building_height_m', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='建物高度（m）')),
                ('project_cost_text', models.CharField(blank=True, default='', max_length=64, verbose_name='工程金額')),
                ('completion_date_text', models.CharField(blank=True, default='', max_length=32, verbose_name='竣工日期')),
                ('start_date_text', models.CharField(blank=True, default='', max_length=32, verbose_name='開工日期')),
                ('law_summary', models.TextField(blank=True, default='', verbose_name='適用法令概要')),
                ('change_summary_text', models.TextField(blank=True, default='', verbose_name='變更概要')),
                ('raw', models.JSONField(blank=True, default=dict, verbose_name='原始資料（僅備查）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '使用執照',
                'verbose_name_plural': '使用執照',
                'indexes': [models.Index(fields=['permit_year', 'permit_no'], name='hub_buildin_permit__5b2bb7_idx')],
                'constraints': [models.UniqueConstraint(fields=('permit_year', 'permit_no'), name='uq_use_permit_year_no')],
            },
        ),
        migrations.CreateModel(
            name='BuildingUsePermitMiscWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='', verbose_name='雜項工作物說明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('permit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='misc_work', to='hub.buildingusepermit', verbose_name='使用執照')),
            ],
            options={
                'verbose_name': '雜項工作物',
                'verbose_name_plural': '雜項工作物',
            },
        ),
        migrations.CreateModel(
            name='BuildingUsePermitAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField(verbose_name='序號')),
                ('address_text', models.CharField(max_length=512, verbose_name='地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='hub.buildingusepermit', verbose_name='使用執照')),
            ],
            options={
                'verbose_name': '建築地點',
                'verbose_name_plural': '建築地點',
                'ordering': ['seq'],
                'indexes': [models.Index(fields=['permit', 'seq'], name='hub_buildin_permit__c1614a_idx')],
            },
        ),
        migrations.CreateModel(
            name='BuildingUsePermitChangeApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField(verbose_name='序號')),
                ('change_approval_text', models.CharField(blank=True, default='', max_length=128, verbose_name='變使准（原文）')),
                ('change_completion_text', models.CharField(blank=True, default='', max_length=128, verbose_name='變使竣工（原文）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_approvals', to='hub.buildingusepermit', verbose_name='使用執照')),
            ],
            options={
                'verbose_name': '變更核准文號',
                'verbose_name_plural': '變更核准文號',
                'ordering': ['seq'],
                'indexes': [models.Index(fields=['permit', 'seq'], name='hub_buildin_permit__7033e8_idx')],
            },
        ),
        migrations.CreateModel(
            name='BuildingUsePermitFloor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField(verbose_name='序號')),
                ('floor_text', models.TextField(verbose_name='樓層（原文）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='hub.buildingusepermit', verbose_name='使用執照')),
            ],
            options={
                'verbose_name': '建築概要',
                'verbose_name_plural': '建築概要',
                'ordering': ['seq'],
                'indexes': [models.Index(fields=['permit', 'seq'], name='hub_buildin_permit__192ba0_idx')],
            },
        ),
        migrations.CreateModel(
            name='BuildingUsePermitNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField(verbose_name='序號')),
                ('note_text', models.TextField(verbose_name='備註說明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='hub.buildingusepermit', verbose_name='使用執照')),
            ],
            options={
                'verbose_name': '注意事項',
                'verbose_name_plural': '注意事項',
                'ordering': ['seq'],
                'indexes': [models.Index(fields=['permit', 'seq'], name='hub_buildin_permit__c755a9_idx')],
            },
        ),
        migrations.CreateModel(
            name='BuildingUsePermitParcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField(verbose_name='序號')),
                ('parcel_text', models.CharField(max_length=256, verbose_name='地段號（原文）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='hub.buildingusepermit', verbose_name='使用執照')),
            ],
            options={
                'verbose_name': '地段地號',
                'verbose_name_plural': '地段地號',
                'ordering': ['seq'],
                'indexes': [models.Index(fields=['permit', 'seq'], name='hub_buildin_permit__ac9dbc_idx')],
            },
        ),
        migrations.CreateModel(
            name='BuildingUsePermitParking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField(verbose_name='序號')),
                ('parking_text', models.TextField(verbose_name='停車空間說明（原文）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parkings', to='hub.buildingusepermit', verbose_name='使用執照')),
            ],
            options={
                'verbose_name': '停車空間',
                'verbose_name_plural': '停車空間',
                'ordering': ['seq'],
                'indexes': [models.Index(fields=['permit', 'seq'], name='hub_buildin_permit__5888c2_idx')],
            },
        ),
    ]
