# Generated by Django 6.0.1 on 2026-01-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0006_buildingusepermit_buildingusepermitmiscwork_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingusepermit',
            name='build_type',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='建造類別'),
        ),
        migrations.AlterField(
            model_name='buildingusepermit',
            name='contractor',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='承造人'),
        ),
        migrations.AlterField(
            model_name='buildingusepermit',
            name='designer',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='設計人'),
        ),
        migrations.AlterField(
            model_name='buildingusepermit',
            name='original_permit_no',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='原核發執照'),
        ),
        migrations.AlterField(
            model_name='buildingusepermit',
            name='structure_type',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='構造種類'),
        ),
        migrations.AlterField(
            model_name='buildingusepermit',
            name='supervisor',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='監造人'),
        ),
        migrations.AlterField(
            model_name='buildingusepermit',
            name='zoning',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='使用分區'),
        ),
    ]
