# Generated by Django 6.0.1 on 2026-01-15 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0007_alter_buildingusepermit_build_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingpermit',
            name='block_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='幢數'),
        ),
        migrations.AddField(
            model_name='buildingpermit',
            name='building_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='棟數'),
        ),
        migrations.AddField(
            model_name='buildingpermit',
            name='floors_above',
            field=models.IntegerField(blank=True, null=True, verbose_name='地上層數'),
        ),
        migrations.AddField(
            model_name='buildingpermit',
            name='floors_below',
            field=models.IntegerField(blank=True, null=True, verbose_name='地下層數'),
        ),
        migrations.AddField(
            model_name='buildingpermit',
            name='unit_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='戶數'),
        ),
        migrations.CreateModel(
            name='BuildingPermitAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField(verbose_name='序號')),
                ('address_text', models.CharField(max_length=512, verbose_name='地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='hub.buildingpermit', verbose_name='建築執照')),
            ],
            options={
                'verbose_name': '建築地點',
                'verbose_name_plural': '建築地點',
                'ordering': ['seq'],
                'indexes': [models.Index(fields=['permit', 'seq'], name='hub_buildin_permit__0b48f6_idx')],
            },
        ),
        migrations.CreateModel(
            name='BuildingPermitFloor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField(verbose_name='序號')),
                ('floor_text', models.TextField(verbose_name='樓層（原文）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='hub.buildingpermit', verbose_name='建築執照')),
            ],
            options={
                'verbose_name': '建築概要',
                'verbose_name_plural': '建築概要',
                'ordering': ['seq'],
                'indexes': [models.Index(fields=['permit', 'seq'], name='hub_buildin_permit__94c4b9_idx')],
            },
        ),
        migrations.CreateModel(
            name='BuildingPermitMiscWorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField(verbose_name='序號')),
                ('misc_text', models.TextField(verbose_name='雜項工作物說明（原文）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='misc_items', to='hub.buildingpermit', verbose_name='建築執照')),
            ],
            options={
                'verbose_name': '雜項工作物',
                'verbose_name_plural': '雜項工作物',
                'ordering': ['seq'],
                'indexes': [models.Index(fields=['permit', 'seq'], name='hub_buildin_permit__be00d3_idx')],
            },
        ),
        migrations.CreateModel(
            name='BuildingPermitNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField(verbose_name='序號')),
                ('note_text', models.TextField(verbose_name='備註說明（原文）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_items', to='hub.buildingpermit', verbose_name='建築執照')),
            ],
            options={
                'verbose_name': '注意事項',
                'verbose_name_plural': '注意事項',
                'ordering': ['seq'],
                'indexes': [models.Index(fields=['permit', 'seq'], name='hub_buildin_permit__80746d_idx')],
            },
        ),
        migrations.CreateModel(
            name='BuildingPermitParcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField(verbose_name='序號')),
                ('parcel_text', models.CharField(max_length=256, verbose_name='地段地號（原文）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='hub.buildingpermit', verbose_name='建築執照')),
            ],
            options={
                'verbose_name': '地段地號',
                'verbose_name_plural': '地段地號',
                'ordering': ['seq'],
                'indexes': [models.Index(fields=['permit', 'seq'], name='hub_buildin_permit__aa3a9c_idx')],
            },
        ),
    ]
